import 'jsr:@supabase/functions-js/edge-runtime.d.ts';

import { askClaude, SAFETY_PREAMBLE } from '../_shared/claude.ts';
import { HttpError, json, serve } from '../_shared/http.ts';
import { logConversation, readBody, requireUser, userClient } from '../_shared/supa.ts';

interface Body {
  lab_value_id?: string;
}

interface Interpretation {
  summary: string;
  markers: Array<{
    name: string;
    value: string;
    status: 'low' | 'low_normal' | 'optimal' | 'high_normal' | 'high' | 'unknown';
    what_it_means: string;
  }>;
  lifestyle_suggestions: string[];
  discuss_with_clinician: string[];
  retest_guidance: string;
}

const SCHEMA = {
  type: 'object',
  required: [
    'summary',
    'markers',
    'lifestyle_suggestions',
    'discuss_with_clinician',
    'retest_guidance',
  ],
  properties: {
    summary: {
      type: 'string',
      description:
        'Two or three sentences on the overall picture, in plain language.',
    },
    markers: {
      type: 'array',
      description: 'Only markers that were actually provided. Skip nulls.',
      items: {
        type: 'object',
        required: ['name', 'value', 'status', 'what_it_means'],
        properties: {
          name: { type: 'string' },
          value: { type: 'string', description: 'Value with its unit.' },
          status: {
            type: 'string',
            enum: ['low', 'low_normal', 'optimal', 'high_normal', 'high', 'unknown'],
          },
          what_it_means: {
            type: 'string',
            description: 'One or two sentences a non-clinician can act on.',
          },
        },
      },
    },
    lifestyle_suggestions: {
      type: 'array',
      items: { type: 'string' },
      description:
        'Diet, sleep, movement and sunlight changes only. Never medication changes.',
    },
    discuss_with_clinician: {
      type: 'array',
      items: { type: 'string' },
      description:
        'Anything that warrants a professional opinion. Empty array if nothing does.',
    },
    retest_guidance: {
      type: 'string',
      description: 'When a repeat test would be informative, and why.',
    },
  },
} as const;

Deno.serve(serve(async (req) => {
  const supabase = userClient(req);
  const user = await requireUser(supabase);
  const { lab_value_id: labId } = await readBody<Body>(req);

  if (!labId) throw new HttpError(400, 'lab_value_id is required');

  const { data: lab, error: labError } = await supabase
    .from('lab_values')
    .select('*')
    .eq('id', labId)
    .maybeSingle();

  if (labError) throw new HttpError(500, labError.message);
  if (!lab) throw new HttpError(404, 'Lab result not found');

  const { data: profile } = await supabase
    .from('health_profiles')
    .select(
      'age, gender, primary_goal, health_conditions, medications, dietary_restrictions',
    )
    .maybeSingle();

  // Send only the markers that were actually recorded — nulls invite invention.
  const measured = Object.fromEntries(
    Object.entries(lab).filter(([key, value]) =>
      value !== null &&
      !['id', 'user_id', 'created_at', 'ai_interpretation', 'notes'].includes(key)
    ),
  );

  const { data: interpretation, tokens } = await askClaude<Interpretation>({
    system: `${SAFETY_PREAMBLE}

You are explaining blood work to an intelligent non-clinician. Distinguish
between "inside the reference range" and "optimal" where the evidence supports
it, but do not overstate contested optimal ranges. Reference ranges vary by
lab, assay and population — flag that where it matters. If a value looks
markedly out of range, say clearly that it warrants a clinician's review.

Only discuss markers you were given. Never estimate a marker that is absent.`,
    content: [{
      type: 'text',
      text: `Lab panel:\n${JSON.stringify(measured, null, 2)}\n\nUser profile:\n${
        JSON.stringify(profile ?? {}, null, 2)
      }\n\nUser's own notes: ${lab.notes ?? 'none'}`,
    }],
    toolName: 'record_lab_interpretation',
    toolDescription: 'Record a plain-language interpretation of this lab panel.',
    schema: SCHEMA,
    maxTokens: 2500,
  });

  const stored = {
    ...interpretation,
    disclaimer:
      'Generated by Bas for education only. Not a diagnosis. Discuss results with a qualified clinician.',
    generated_at: new Date().toISOString(),
  };

  const { error: updateError } = await supabase
    .from('lab_values')
    .update({ ai_interpretation: stored })
    .eq('id', labId);

  if (updateError) throw new HttpError(500, updateError.message);

  await logConversation(supabase, user.id, {
    triggerType: 'lab_interpretation',
    triggerContext: { lab_value_id: labId, test_name: lab.test_name },
    response: interpretation.summary,
    tokens,
  });

  return json({ lab_value_id: labId, interpretation: stored });
}));
